spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          batch_size: 10
        order_updates: true
    show-sql: false
  flyway:
    enabled: true
    out-of-order: true
    repair: true
    locations: classpath:/db/migrations

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
  profiles:
    active: beta
springdoc:
  api-docs:
    path: /v3/api-docs
app:
  jwt-secret: ${JWT_SECRET:1e402ebbb616551c23af31108b49364249c62d4712d31cbab8309b6d8fef253c}
  credentials: ${GOOGLE_APPLICATION_CREDENTIALS:alert-vim-443402-u5-6b0c8b68374a.json}
app-jwt-expiration-milliseconds: 604800000
server:
  port: ${PORT:8080}
